### ISSUE TITLE
Issue with external reference "Failed to open stream: No such file or directory"

### ISSUE THREAD

**Issue by scramatte** [fidum/nova-package-bundler-command#13]
Hi,

It looks that one of my packages has a reference to https://www.unpkg.com/tailwindcss@0.7.4/dist/tailwind.css that throws an error with your tool.

The following code throws the error:
```php
        Nova::serving(function (ServingNova $event) {
            ...
            Nova::remoteStyle('https://www.unpkg.com/tailwindcss@0.7.4/dist/tailwind.css');
        });
```

![image](https://github.com/fidum/nova-package-bundler-command/assets/188766/16f41468-dd33-498e-a080-941851ef0228)

Can you fix it ?

Regards

**Comment by dmason30** [comment]
Why would a package include the whole tailwindcss and a version of tailwindcss that does not match the version nova is using?

Please can you provide a link to the package? If this is your private package, you really shouldn't be getting tailwindcss like this.

I will see if i can avoid the error..
