### ISSUE TITLE
Feature request: exclude specific assets

### ISSUE THREAD

**Issue by sanderbaas** [fidum/nova-package-bundler-command#19]
When I am developing a nova-component locally I disable usage of the bundled assets. Otherwise I cannot see what I am doing. However, this is slowing done reloading pages significantly. It would be great if I can just exclude the component I am currently developing, so other assets are bundled and load quickly.

**Comment by dmason30** [comment]
I suppose you maybe able to do this with an array of asset keys in the config you want to ignore. 

Feel free to submit a PR with tests.

**Comment by sanderbaas** [comment]
@dmason30 Hi Dan, I would like to create a new github issue about supporting laravel 13, but I'm in some sort of github redirect loop when selecting the issue category. So I thought I'd reach out to you like this.
