### ISSUE TITLE
Bundle css contained into .vue components?

### ISSUE THREAD

**Issue by scramatte** [fidum/nova-package-bundler-command#29]
Hi,

Does it possible to bundle css that are located into .vue components?

My app use lot of components resulting such kind of code

![imagen](https://github.com/fidum/nova-package-bundler-command/assets/188766/c2f9ce21-0cbe-484e-bd40-39e1db2dd93d)

Regards

**Comment by dmason30** [comment]
Sorry, this package can only bundle assets registered with nova.
