### ISSUE TITLE
Minify JavaScript and css

### ISSUE THREAD

**Issue by scramatte** [fidum/nova-package-bundler-command#33]
Hello,

Sorry to open an issue for that, but the other sections are not available (404 error)
Can you add a feature to minify Javascript and Css code ?

I've made a separate command using  'https://github.com/matthiasmullie/minify'  to minimize 'public/vendor/nova-tools/app.css'. It looks that works, but depth tests are required.

I've tried too with Javascript and my 18M app.js get down to 6M ...   It looks that nova still working after this. 

Note that I've enabled gzip and http2 on my nginx server too. The user experience improve a lot !

Regards

**Comment by scramatte** [comment]
Javascript shrinking has come issues.  I've rebuilt my local components for prod and without extra shrink the code get down for 18M o 9M.   But problaby we can improve it !

**Comment by dmason30** [comment]
@scramatte I am curious what your bundling with this that is not already minified? 

Ideally all registered assets in Nova should already be minified? 

I suppose third party packages may be out of your control to an extent but they should be updated to register already minified assets.
